### ISSUE TITLE
Crash when TCPClient connect failed

### ISSUE THREAD

**Issue by liwei-ch** [Qihoo360/evpp#7]
gdb bt:
```
#0  0x00007ffc5fbed3c0 in evpp::TCPConn::IsDisconnected (this=0x0) at /home/liwei/github.com/qihoo360/evpp/evpp/tcp_conn.h:77
77          return status_ == kDisconnected;
Missing separate debuginfos, use: debuginfo-install gflags-1.6-1.el6.x86_64 glibc-2.12-1.166.el6_7.3.x86_64 glog-0.3.3-1.el6.x86_64 libevent20-2.0.21-13.el6.x86_64 libgcc-4.4.7-16.el6.x86_64 libstdc++-4.4.7-16.el6.x86_64
(gdb) bt
# 0  0x00007ffc5fbed3c0 in evpp::TCPConn::IsDisconnected (this=0x0) at /home/liwei/github.com/qihoo360/evpp/evpp/tcp_conn.h:77
#2 1  0x00007ffc5fbec159 in evpp::TCPClient::~TCPClient (this=0x22bdff0, __in_chrg=<value optimized out>) at /home/liwei/github.com/qihoo360/evpp/evpp/tcp_client.cc:25
#2  0x000000000047893e in std::_Sp_counted_ptr<evpp::TCPClient*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x22bde50)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr_base.h:290
#3  0x00000000004572ee in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x22bde50)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
#4  0x00000000004563cf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x22bdd70, __in_chrg=<value optimized out>)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr_base.h:546
#5  0x0000000000475d6a in std::__shared_ptr<evpp::TCPClient, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x22bdd68, __in_chrg=<value optimized out>)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr_base.h:781
#6  0x0000000000475da2 in std::shared_ptr<evpp::TCPClient>::~shared_ptr (this=0x22bdd68, __in_chrg=<value optimized out>)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr.h:93
#7  0x0000000000472aac in evnsq::NSQConn::~NSQConn (this=0x22bdcf0, __in_chrg=<value optimized out>) at /home/liwei/github.com/qihoo360/evpp/apps/evnsq/nsq_conn.cc:31
#8  0x0000000000472748 in std::_Sp_counted_ptr<evnsq::NSQConn*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x22be4a0)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr_base.h:290
#9  0x00000000004572ee in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x22be4a0)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
#10 0x00000000004563cf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x22be830, __in_chrg=<value optimized out>)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr_base.h:546
#11 0x000000000045a138 in std::__shared_ptr<evnsq::NSQConn, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x22be828, __in_chrg=<value optimized out>)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr_base.h:781
#12 0x000000000045a152 in std::shared_ptr<evnsq::NSQConn>::~shared_ptr (this=0x22be828, __in_chrg=<value optimized out>)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/shared_ptr.h:93
#13 0x00000000004658b0 in evnsq::Client::__lambda2::~<lambda>(void) (this=0x22be820, __in_chrg=<value optimized out>)
    at /home/liwei/github.com/qihoo360/evpp/apps/evnsq/client.cc:177
#14 0x00000000004668d5 in std::_Function_base::_Base_manager<evnsq::Client::OnConnection(const ConnPtr&)::__lambda2>::_M_destroy(std::_Any_data &, std::false_type) (__victim=...)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/functional:1926
#15 0x000000000046655d in std::_Function_base::_Base_manager<evnsq::Client::OnConnection(const ConnPtr&)::__lambda2>::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=std::__destroy_functor) at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/functional:1950
#16 0x0000000000455dcb in std::_Function_base::~_Function_base (this=0x22be7f0, __in_chrg=<value optimized out>) at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/functional:2030
#17 0x0000000000456108 in std::function<void()>::~function(void) (this=0x22be7f0, __in_chrg=<value optimized out>)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/functional:2174
#18 0x00007ffc5fc08627 in std::_Destroy<std::function<void()> >(std::function<void()> *) (__pointer=0x22be7f0)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/stl_construct.h:93
#19 0x00007ffc5fc083f4 in std::_Destroy_aux<false>::__destroy<std::function<void()>*>(std::function<void()> *, std::function<void()> *) (__first=0x22be7f0, __last=0x22be810)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/stl_construct.h:103
#20 0x00007ffc5fc08011 in std::_Destroy<std::function<void()>*>(std::function<void()> *, std::function<void()> *) (__first=0x22be7f0, __last=0x22be810)
    at /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/stl_construct.h:126
#21 0x00007ffc5fc07995 in std::_Destroy<std::function<void()>*, std::function<void()> >(std::function<void()> *, std
```
the logs:
E0316 19:32:06.652880 11996 connector.cc:134] status=kConnecting fd=7 errno=111 Connection refused
I0316 19:32:06.652945 11996 fd_channel.cc:112] DetachFromLoop this=0xc6f580 fd=7 detach from event loop
I0316 19:32:06.652988 11996 tcp_client.cc:71] Failed to connect to 127.0.0.1:4150. errno=111 Connection refused
I0316 19:32:06.653022 11996 tcp_conn.cc:32] TCPConn::[] this=0xc6f0a0 channel=0 fd=-1
E0316 19:32:06.653051 11996 nsq_conn.cc:74] Connect to  failed.
I0316 19:32:06.653117 11996 tcp_conn.cc:36] TCPConn::~TCPConn() name= this=0xc6f0a0 channel=0 fd=-1 type=0 status=kDisconnected
I0316 19:32:06.653151 11996 connector.cc:150] Connector::HandleError close(7)

**Comment by zieckey** [comment]
Fixed.
